python -u train_referit3d.py \
    -scannet-file /lustre/scratch/project/k1546/scannet/keep_all_points_00_view_with_global_scan_alignment/keep_all_points_00_view_with_global_scan_alignment.pkl \
    -referit3D-file /home/ahmems0a/CoT3D_VG/refering_codes/SAT/referit3d/data/nr3d_cot_ref_paraphrases_num_anchors.csv \
    --log-dir logs/cot_nr_10%_distractorloss_7anchors_batch64 \
    --patience 100 \
    --max-train-epochs 100 \
    --init-lr 5e-4 \
    --batch-size 64 \
    --transformer \
    --model mmt_referIt3DNet \
    --n-workers 6 \
    --gpu 1 \
    --unit-sphere-norm True \
    --feat2d clsvecROI \
    --context_2d unaligned \
    --mmt_mask train2d \
    --warmup False \
    --anchors "cot" \
    --max-test-objects 52 \
    --cot_type "cross" \
    --predict_lang_anchors True \
    --lang_filter_objs False \
    --visaug_shuffle_mode 'none' \
    --shuffle_objects_percentage 0 \
    --visaug_extracted_obj_path '/home/abdelrem/3d_codes/CoT3D_VG/data/nr3d/' \
    --visaug_pc_augment False \
    --train_data_percent 0.1 \
    --max_num_anchors 7 \
    --dropout-rate 0.15 \
    --textaug_paraphrase_percentage 0 \
    --target_aug_percentage 0 \
    --gaussian_latent False \
    --distractor_aux_loss_flag True \
    --train_data_repeatation 1\
    --scanrefer False \
    --feedGTPath False \
    --multicls_multilabel False \
    --include_anchor_distractors False\