output_dir: ../log/vil_teacher_rerpoduce_nr3d
resume_files: null

world_size: 1
node_rank: -1
local_rank: -1
rank: -1
gpu: 0

seed: 0
num_epoch: 100
batch_size: 128
weight_decay: 0.01
optim: adamw
learning_rate: 0.0005
lr_decay: cosine
txt_encoder_lr_multi: 0.1
obj_encoder_lr_multi: 1
cot_decoder_lr_multi: 0.1
betas: [0.9, 0.98]
warmup_steps: 5000
grad_norm: 5.0
num_workers: 4
val_every_epoch: 1

model:
  model_type: gtlabel
  hidden_size: 768
  dropout: 0.3
  num_obj_classes: 607
  obj_encoder:
    onehot_ft: false
    dim_ft: 300
    dim_loc: 6
    dropout: 0.1
    freeze: false
    freeze_bn: false
    use_color_enc: true
  txt_encoder:
    type: bert # bert, gru
    num_layers: 3
    freeze: false
  mm_encoder:
    type: cmt
    spatial_dec: true
    spatial_multihead: true
    spatial_dim: 5  # 1, 4, 5, 12(mlp)
    spatial_dist_norm: true
    spatial_attn_fusion: cond # mul, bias, ctx, add, cond
    num_layers: 4
    obj_loc_encoding: same_all # same_0, same_all, diff_all
    pairwise_rel_type: center # center, vertical_bottom, mlp
    dim_feedforward: 2048
  losses:
    obj3d_clf: 1
    obj3d_clf_pre: 1
    obj3d_reg: 0
    txt_clf: 1
    cot_teacher_loss: false

dataset:
  is_nr3d: true
  scan_dir: /home/abdelrem/3d_codes/vil3d_preprocessed_data/scan_data
  anno_file: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/bert_tokenized/nr3d.jsonl
  category_file:  /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/meta_data/scannetv2_raw_categories.json
  cat2vec_file: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/meta_data/cat2glove42b.json

  trn_scan_split: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/splits/scannetv2_train.txt
  val_scan_split: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/splits/scannetv2_val.txt
  tst_scan_split: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/splits/scannetv2_test.txt

  max_txt_len: 50
  max_obj_len: 80
  keep_background: false
  random_rotate: true

cot:
  anchors: 'cot'
  cot_type: 'cross'
  predict_lang_anchors: true
  train_data_percent: 1.0
  max_num_anchors: 7
  target_aug_percentage: 0
  distractor_aux_loss_flag: true
  #data_csv_pth: "/home/abdelrem/3d_codes/CoT3D_VG/extract_anchors/nr3d_cot_ref_paraphrases_num_anchors.csv"
  data_csv_pth: "/home/abdelrem/3d_codes/CoT3D_VG/extract_anchors/nr3D_with_TRUE_GT.csv"
  tgt_mul_w: 1
  gaussian_latent: false
  anchors_ids_type: "GT"  # [pseudoWneg_old, pseudoWneg, pseudoWOneg, ourPathGTids, GT]
