output_dir: ../log/vil_teacher_rerpoduce_sr3d
resume_files: null

world_size: 1
node_rank: -1
local_rank: -1
rank: -1
gpu: 3

seed: 0
num_epoch: 25
batch_size: 128
weight_decay: 0.01
optim: adamw
learning_rate: 0.0005
lr_decay: cosine
txt_encoder_lr_multi: 0.1
obj_encoder_lr_multi: 1
cot_decoder_lr_multi: 0.01
betas: [0.9, 0.98]
warmup_steps: 5000
grad_norm: 5.0
num_workers: 4
val_every_epoch: 1

model:
  model_type: gtlabel
  hidden_size: 768
  dropout: 0.3
  num_obj_classes: 607
  obj_encoder:
    onehot_ft: false
    dim_ft: 300
    dim_loc: 6
    dropout: 0.1
    freeze: false
    freeze_bn: false
    use_color_enc: true
  txt_encoder:
    type: bert # bert, gru
    num_layers: 3
    freeze: false
  mm_encoder:
    type: cmt
    spatial_dec: true
    spatial_multihead: true
    spatial_dim: 5  # 1, 4, 5, 12(mlp)
    spatial_dist_norm: true
    spatial_attn_fusion: cond # mul, bias, ctx, add, cond
    num_layers: 4
    obj_loc_encoding: same_all # same_0, same_all, diff_all
    pairwise_rel_type: center # center, vertical_bottom, mlp
  losses:
    obj3d_clf: 1
    obj3d_clf_pre: 1
    obj3d_reg: 0
    txt_clf: 1

dataset:
  is_nr3d: false
  scan_dir: /home/abdelrem/3d_codes/vil3d_preprocessed_data/scan_data
  anno_file: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/bert_tokenized/sr3d.jsonl
  category_file:  /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/meta_data/scannetv2_raw_categories.json
  cat2vec_file: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/meta_data/cat2glove42b.json

  trn_scan_split: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/splits/scannetv2_train.txt
  val_scan_split: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/splits/scannetv2_val.txt
  tst_scan_split: /home/abdelrem/3d_codes/vil3d_preprocessed_data/annotations/splits/scannetv2_test.txt

  max_txt_len: 50
  max_obj_len: 80
  keep_background: false
  random_rotate: true
  
  use_gt_view_in_target: false

cot:
  anchors: 'none'
  cot_type: 'cross'
  predict_lang_anchors: false
  train_data_percent: 1.0
  max_num_anchors: 1
  target_aug_percentage: 0
  distractor_aux_loss_flag: false
  data_csv_pth: "/home/abdelrem/3d_codes/scannet_dataset/scannet/sr3d.csv"
  tgt_mul_w: 1
  gaussian_latent: false